# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 865)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("* {\n"
"    font-size:23px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_ShowCamera = QtWidgets.QLabel(self.groupBox)
        self.label_ShowCamera.setText("")
        self.label_ShowCamera.setPixmap(QtGui.QPixmap("../images/process1.png"))
        self.label_ShowCamera.setScaledContents(False)
        self.label_ShowCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShowCamera.setObjectName("label_ShowCamera")
        self.gridLayout_2.addWidget(self.label_ShowCamera, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_UserName = QtWidgets.QLabel(self.groupBox_2)
        self.label_UserName.setObjectName("label_UserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_UserName)
        self.lineEdit_UserName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_UserName)
        self.label_SelectGender = QtWidgets.QLabel(self.groupBox_2)
        self.label_SelectGender.setObjectName("label_SelectGender")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_SelectGender)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_Male = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Male.setStyleSheet("")
        self.radioButton_Male.setChecked(True)
        self.radioButton_Male.setObjectName("radioButton_Male")
        self.horizontalLayout_4.addWidget(self.radioButton_Male)
        self.radioButton_Female = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Female.setObjectName("radioButton_Female")
        self.horizontalLayout_4.addWidget(self.radioButton_Female)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_SaveReport = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_SaveReport.sizePolicy().hasHeightForWidth())
        self.button_SaveReport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.button_SaveReport.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icons8_save_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_SaveReport.setIcon(icon)
        self.button_SaveReport.setIconSize(QtCore.QSize(45, 45))
        self.button_SaveReport.setFlat(True)
        self.button_SaveReport.setObjectName("button_SaveReport")
        self.verticalLayout_5.addWidget(self.button_SaveReport)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.textEdit_Report = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_Report.setStyleSheet("")
        self.textEdit_Report.setObjectName("textEdit_Report")
        self.verticalLayout.addWidget(self.textEdit_Report)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_CaptureAnalyse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_CaptureAnalyse.sizePolicy().hasHeightForWidth())
        self.button_CaptureAnalyse.setSizePolicy(sizePolicy)
        self.button_CaptureAnalyse.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons8_face_id_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_CaptureAnalyse.setIcon(icon1)
        self.button_CaptureAnalyse.setIconSize(QtCore.QSize(100, 100))
        self.button_CaptureAnalyse.setAutoExclusive(False)
        self.button_CaptureAnalyse.setAutoDefault(False)
        self.button_CaptureAnalyse.setDefault(False)
        self.button_CaptureAnalyse.setFlat(True)
        self.button_CaptureAnalyse.setObjectName("button_CaptureAnalyse")
        self.horizontalLayout_2.addWidget(self.button_CaptureAnalyse)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_NormalImage = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_NormalImage.setChecked(True)
        self.radioButton_NormalImage.setAutoRepeatDelay(300)
        self.radioButton_NormalImage.setObjectName("radioButton_NormalImage")
        self.horizontalLayout_7.addWidget(self.radioButton_NormalImage)
        self.radioButton_FaceTract = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_FaceTract.setCheckable(True)
        self.radioButton_FaceTract.setObjectName("radioButton_FaceTract")
        self.horizontalLayout_7.addWidget(self.radioButton_FaceTract)
        self.radioButton_EdgeTract = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_EdgeTract.setCheckable(True)
        self.radioButton_EdgeTract.setObjectName("radioButton_EdgeTract")
        self.horizontalLayout_7.addWidget(self.radioButton_EdgeTract)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalSlider_EdgeTract = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_EdgeTract.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.horizontalSlider_EdgeTract.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_EdgeTract.setSizePolicy(sizePolicy)
        self.horizontalSlider_EdgeTract.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider_EdgeTract.setAutoFillBackground(False)
        self.horizontalSlider_EdgeTract.setProperty("value", 0)
        self.horizontalSlider_EdgeTract.setSliderPosition(0)
        self.horizontalSlider_EdgeTract.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_EdgeTract.setInvertedAppearance(False)
        self.horizontalSlider_EdgeTract.setInvertedControls(False)
        self.horizontalSlider_EdgeTract.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_EdgeTract.setTickInterval(0)
        self.horizontalSlider_EdgeTract.setObjectName("horizontalSlider_EdgeTract")
        self.verticalLayout_4.addWidget(self.horizontalSlider_EdgeTract)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/GDPUlogo_outline.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/icons8_photo_gallery_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenImage.setIcon(icon2)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionOpenCamera = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/icons8_camera_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenCamera.setIcon(icon3)
        self.actionOpenCamera.setObjectName("actionOpenCamera")
        self.actionCloseCamera = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/icons8_no_camera_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCloseCamera.setIcon(icon4)
        self.actionCloseCamera.setObjectName("actionCloseCamera")
        self.actionClearImage = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/icons8_delete_48px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearImage.setIcon(icon5)
        self.actionClearImage.setObjectName("actionClearImage")
        self.toolBar.addAction(self.actionOpenImage)
        self.toolBar.addAction(self.actionOpenCamera)
        self.toolBar.addAction(self.actionCloseCamera)
        self.toolBar.addAction(self.actionClearImage)

        self.retranslateUi(MainWindow)
        self.radioButton_EdgeTract.toggled['bool'].connect(self.horizontalSlider_EdgeTract.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "展示区："))
        self.groupBox_2.setTitle(_translate("MainWindow", "报告区："))
        self.label_UserName.setText(_translate("MainWindow", "姓名："))
        self.label_SelectGender.setText(_translate("MainWindow", "性别："))
        self.radioButton_Male.setText(_translate("MainWindow", "男"))
        self.radioButton_Female.setText(_translate("MainWindow", "女"))
        self.button_SaveReport.setText(_translate("MainWindow", "保存报告"))
        self.groupBox_3.setTitle(_translate("MainWindow", "图像模式："))
        self.radioButton_NormalImage.setText(_translate("MainWindow", "正常图像"))
        self.radioButton_FaceTract.setText(_translate("MainWindow", "人脸捕捉"))
        self.radioButton_EdgeTract.setText(_translate("MainWindow", "边缘检测"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenImage.setText(_translate("MainWindow", "OpenImage"))
        self.actionOpenImage.setToolTip(_translate("MainWindow", "打开图片"))
        self.actionOpenCamera.setText(_translate("MainWindow", "OpenCamera"))
        self.actionOpenCamera.setToolTip(_translate("MainWindow", "打开摄像头"))
        self.actionCloseCamera.setText(_translate("MainWindow", "CloseCamera"))
        self.actionCloseCamera.setToolTip(_translate("MainWindow", "关闭摄像头"))
        self.actionClearImage.setText(_translate("MainWindow", "CleanImage"))
        self.actionClearImage.setToolTip(_translate("MainWindow", "清除图像"))

